name: Build and Publish
on:
  push:
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: [3.1.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Test
        run: dotnet test -c Release --verbosity normal

  apidoc:
    name: Publish API Documentation
    runs-on: ubuntu-latest

    # Runs only on commits to master
    if: github.ref == 'refs/heads/master'
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build API documentation
        uses: nikeee/docfx-action@master
        with:
          args: docs/docfx.json

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/_site
          TARGET_FOLDER: apidoc
          CLEAN: true

  nuget:
    name: Publish NuGet Packages
    runs-on: windows-latest

    # Runs only on commits to master or when creating a tag
    if: github.ref == 'refs/heads/master' || contains(github.ref, 'refs/tags/')
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.1

      - name: Create Package
        if: github.ref == 'refs/heads/master'
        run: |
          $buildNumber=git rev-parse --short HEAD
          dotnet pack src/MarcusW.VncClient -c Release -o packages -p:BuildNumber=$buildNumber
          dotnet pack src/MarcusW.VncClient.Avalonia -c Release -o packages -p:BuildNumber=$buildNumber

      - name: Create Release-Package
        if: contains(github.ref, 'refs/tags/')
        run: |
          dotnet pack src/MarcusW.VncClient -c Release -o packages
          dotnet pack src/MarcusW.VncClient.Avalonia -c Release -o packages

      # Use Windows to push using nuget.exe because GitHub Packages is broken: https://stackoverflow.com/a/63935703/5495384
      - name: Push to GitHub Packages
        run: nuget.exe push packages\*.nupkg -SkipDuplicate

      - name: Push to nuget.org
        if: contains(github.ref, 'refs/tags/')
        run: dotnet nuget push "packages/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: packages\
