name: Build
on:
  - push
  - pull_request
  - release:
      types: [published]

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: [3.1.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Test
        run: dotnet test -c Release --verbosity normal

  apidoc:
    name: Publish API Documentation
    runs-on: ubuntu-latest

    # Runs only on commits to master
    if: github.ref == 'refs/heads/master'
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build API documentation
        uses: nikeee/docfx-action@master
        with:
          args: docs/docfx.json

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/_site
          TARGET_FOLDER: apidoc
          CLEAN: true

  nuget:
    name: Publish NuGet Packages
    runs-on: ubuntu-latest

    # Runs only on commits to master or when publishing a release
    if: github.ref == 'refs/heads/master' || github.event_name == 'release'
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Create Package
        if: github.ref == 'refs/heads/master'
        run: |
          BUILD_NUMBER=${{ github.sha }}
          dotnet pack src/MarcusW.VncClient -c Release -o packages -p:BuildNumber=$BUILD_NUMBER
          dotnet pack src/MarcusW.VncClient.Avalonia -c Release -o packages -p:BuildNumber=$BUILD_NUMBER

      - name: Create Release-Package
        if: github.event_name == 'release'
        run: |
          dotnet pack src/MarcusW.VncClient -c Release -o packages
          dotnet pack src/MarcusW.VncClient.Avalonia -c Release -o packages
