name: Build
on:
  - push

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # Static version numbering because of https://github.com/actions/setup-dotnet/issues/23
        # See https://github.com/dotnet/core/blob/master/release-notes/releases-index.json
        dotnet: [3.0.103, 3.1.201]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

  apidoc:
    name: API documentation
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build API documentation
        uses: nikeee/docfx-action@master
        with:
          args: docs/docfx.json

      - name: Debug
        run: tree

      - name: Deploy to GitHub pages
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            BRANCH: gh-pages
            FOLDER: docs/_site
            GIT_CONFIG_NAME: DocFX Generator
            TARGET_FOLDER: apidoc
            CLEAN: true
